version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgres://postgres:BtG9uJVtfPtcF74@localhost:5432/postgres
